# Generated by Django 2.0.1 on 2018-02-03 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('desc', models.CharField(max_length=50, verbose_name='描述')),
                ('pub_date', models.DateField(verbose_name='date published')),
                ('address', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, null=True)),
                ('student_nickname', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(default='000', max_length=30, null=True)),
                ('thu_email', models.CharField(max_length=20, null=True)),
                ('profile_photo', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='TeamInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=30, null=True)),
                ('leader', models.CharField(max_length=50, null=True)),
                ('invite_code', models.CharField(max_length=20, null=True)),
                ('codes', models.TextField(null=True)),
                ('history', models.TextField(null=True)),
                ('score', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='team_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.TeamInfo'),
        ),
    ]
