# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-21 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20180203_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='DockerServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField(null=True)),
                ('is_busy', models.BooleanField(default=False)),
                ('battle_id', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='is_leader',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='salt',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='teaminfo',
            name='battle_code',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='teaminfo',
            name='battle_time',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='teaminfo',
            name='member1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teaminfo',
            name='member2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teaminfo',
            name='member3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teaminfo',
            name='member_num',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='password',
            field=models.CharField(default='000', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='thu_email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teaminfo',
            name='history',
            field=models.CharField(default='[]', max_length=8000),
        ),
        migrations.AlterField(
            model_name='teaminfo',
            name='score',
            field=models.CharField(default='[]', max_length=800),
        ),
    ]
