# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-21 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20180321_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='student_realname',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
