# Generated by Django 2.0.3 on 2018-03-23 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_studentinfo_student_realname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaminfo',
            name='score',
            field=models.CharField(default='[{"score":50}]', max_length=800),
        ),
    ]
